In [ ]:
import panel as pn
from main import app


app.servable()

In [1]:
# Célula de Teste e Inspeção do Dia 6
from dao.relatorios_dao import obter_df_engajamento_grupos, obter_df_status_encontros

print("📊 Relatório 1: Engajamento dos Grupos (Membro A)")
df_engajamento = obter_df_engajamento_grupos()
display(df_engajamento) 

print("\n-------------------------------------------------\n")

print("📈 Relatório 2: Status dos Encontros (Membro B)")
df_status = obter_df_status_encontros()
display(df_status)

📊 Relatório 1: Engajamento dos Grupos (Membro A)
2026-06-13 09:40:47,706 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2026-06-13 09:40:47,707 INFO sqlalchemy.engine.Engine [raw sql] {}
2026-06-13 09:40:47,711 INFO sqlalchemy.engine.Engine select current_schema()
2026-06-13 09:40:47,712 INFO sqlalchemy.engine.Engine [raw sql] {}
2026-06-13 09:40:47,714 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2026-06-13 09:40:47,715 INFO sqlalchemy.engine.Engine [raw sql] {}
2026-06-13 09:40:47,720 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2026-06-13 09:40:47,722 INFO sqlalchemy.engine.Engine
        SELECT
            g.nome AS "Nome do Grupo",
            COUNT(DISTINCT e.id_encontro) AS "Total de Encontros",
            COUNT(DISTINCT m.id_mensagem) AS "Total de Mensagens"
        FROM grupo g
        LEFT JOIN encontro e ON g.id_grupo = e.id_grupo
        LEFT JOIN mensagem m ON g.id_grupo = e.id_grupo
        GROUP BY g.nome
        ORDER BY "Total de Encontros" DESC, "Total de Mensagens" DESC;

2026-06-13 09:40:47,724 INFO sqlalchemy.engine.Engine [generated in 0.00434s] {}
2026-06-13 09:40:47,740 INFO sqlalchemy.engine.Engine ROLLBACK

  Nome do Grupo  Total de Encontros  Total de Mensagens
0       ES 2026                   1                   1

-------------------------------------------------

📈 Relatório 2: Status dos Encontros (Membro B)
2026-06-13 09:40:47,794 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2026-06-13 09:40:47,796 INFO sqlalchemy.engine.Engine
        SELECT
            status AS "Status",
            COUNT(id_encontro) AS "Qtd. de Encontros",
            COALESCE(SUM(limite_participantes), 0) AS "Vagas Ofertadas"
        FROM encontro
        GROUP BY status
        ORDER BY "Qtd. de Encontros" DESC;

2026-06-13 09:40:47,800 INFO sqlalchemy.engine.Engine [generated in 0.00610s] {}
2026-06-13 09:40:47,808 INFO sqlalchemy.engine.Engine ROLLBACK

         Status  Qtd. de Encontros  Vagas Ofertadas
0  EM_ANDAMENTO                  1                2